# Generated by Django 3.2.9 on 2021-11-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant_form', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantForm',
            fields=[
                ('form_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('public_bio', models.TextField()),
                ('chess_experience', models.TextField()),
                ('personal_statement', models.TextField()),
                ('aim_club', models.TextField()),
                ('pub_date', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='email',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='personal_statement',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='public_bio',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='Chess_Experience_Level',
        ),
        migrations.DeleteModel(
            name='Email',
        ),
        migrations.DeleteModel(
            name='Name',
        ),
        migrations.DeleteModel(
            name='Personal_Statement',
        ),
        migrations.DeleteModel(
            name='Public_Bio',
        ),
    ]
